# Site settings
title: Sobala Werbung
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# Google-analytics
google-analytics:
  id: ""

sass:
  style: compressed
